import Head from "next/head";
import Image from "next/image";
import Banner from "../components/banner/banner";
import Card from "../components/card/card";
import SectionCards from "../components/card/section-cards";
import NavBar from "../components/nav/navbar";
import { getVideos } from "../lib/videos";
import styles from "../styles/Home.module.css";

export default function Home() {
  const disneyVideos = getVideos();
  return (
    <div className={styles.container}>
      <Head>
        <title>Netflix Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar username="Pedro Diaz" />
      <Banner
        title="Clifford the red dog"
        subTitle="a very cute dog"
        imgUrl="/static/clifford.webp"
      />
      <div className={styles.sectionWrapper}>
        <SectionCards title={"Disney"} videos={disneyVideos} size="large" />
        <SectionCards title={"Disney"} videos={disneyVideos} size="medium" />
        <SectionCards title={"Disney"} videos={disneyVideos} size="small" />
      </div>
    </div>
  );
}
